---

vault:
  csi:
    enabled: true
    image:
      repository: quay.io/bradfordwagner/vault
      tag: 1.3.0-vault-csi-driver-1.4.0
  injector:
    enabled: true
    image:
      repository: quay.io/bradfordwagner/vault
      tag: 1.3.0-vault-webhook-injector-1.2.1
  server:
    extraEnvironmentVars:
       # VAULT_CACERT: /vault/userconfig/tls/vault.ca
       VAULT_TLSCERT: /vault/userconfig/tls/certificate
       VAULT_TLSKEY: /vault/userconfig/tls/private_key
    volumes:
       - name: tls
         secret:
          defaultMode: 420
          secretName: tls
    volumeMounts:
       - mountPath: /vault/userconfig/tls
         name: tls
         readOnly: true

    image:
      repository: quay.io/bradfordwagner/vault
      tag: 1.3.0-vault-1.14.0
    service:
      type: NodePort
      nodePort: 30003
    dataStorage:
      enabled: false # noto needed since we arae using azure blob
    standalone:
      config: |
        ui = true
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        seal "azurekeyvault" {}

    # reference storage defined in tf cicd - this is in order to hide credentials
    # based on: https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
    extraArgs: -config=/vault/userconfig/storage/config.hcl
    extraVolumes:
      - type: secret
        name: storage

    extraSecretEnvironmentVars:
      - secretName: keyvault
        envName: AZURE_TENANT_ID
        secretKey: AZURE_TENANT_ID
      - secretName: keyvault
        envName: AZURE_CLIENT_ID
        secretKey: AZURE_CLIENT_ID
      - secretName: keyvault
        envName: AZURE_CLIENT_SECRET
        secretKey: AZURE_CLIENT_SECRET
      - secretName: keyvault
        envName: VAULT_AZUREKEYVAULT_VAULT_NAME
        secretKey: VAULT_AZUREKEYVAULT_VAULT_NAME
      - secretName: keyvault
        envName: VAULT_AZUREKEYVAULT_KEY_NAME
        secretKey: VAULT_AZUREKEYVAULT_KEY_NAME

