---

vault:
  csi:
    enabled: true
    image:
      repository: quay.io/bradfordwagner/vault
      tag: 1.1.1-vault-csi-driver-1.1.0
  injector:
    enabled: true
  server:
    image:
      repository: quay.io/bradfordwagner/vault
      tag: 1.0.0-vault-1.9.4
    service:
      type: NodePort
      nodePort: 30003
    dataStorage:
      enabled: false # noto needed since we arae using azure blob
    standalone:
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        seal "azurekeyvault" {}

    # reference storage defined in tf cicd - this is in order to hide credentials
    # based on: https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
    extraArgs: -config=/vault/userconfig/storage/config.hcl
    extraVolumes:
      - type: secret
        name: storage

    extraSecretEnvironmentVars:
      - secretName: keyvault
        envName: AZURE_TENANT_ID
        secretKey: AZURE_TENANT_ID
      - secretName: keyvault
        envName: AZURE_CLIENT_ID
        secretKey: AZURE_CLIENT_ID
      - secretName: keyvault
        envName: AZURE_CLIENT_SECRET
        secretKey: AZURE_CLIENT_SECRET
      - secretName: keyvault
        envName: VAULT_AZUREKEYVAULT_VAULT_NAME
        secretKey: VAULT_AZUREKEYVAULT_VAULT_NAME
      - secretName: keyvault
        envName: VAULT_AZUREKEYVAULT_KEY_NAME
        secretKey: VAULT_AZUREKEYVAULT_KEY_NAME

