apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-chart-vault-
spec:
  ttlStrategy:
    secondsAfterCompletion: 3600 # delete workflow after 1 hour
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
      value: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    dag:
      tasks:
      - name: helm
        arguments:
          parameters:
          - name: git_ref_type
            value: "{{ inputs.parameters.git_ref_type }}"
          - name: git_repo
            value: https://github.com/bradfordwagner/deploy-chart-vault.git
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: helm_image
            value: quay.io/bradfordwagner/helm:1.0.0-debian_bullseye
          - name: csi_class
            value: acr-prod
        templateRef:
          name: flavor-helm-template
          template: main

